//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peace_Portal_Payroll.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.3300")]
        public string Rate1 {
            get {
                return ((string)(this["Rate1"]));
            }
            set {
                this["Rate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37.995")]
        public string Rate2 {
            get {
                return ((string)(this["Rate2"]));
            }
            set {
                this["Rate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50.6600")]
        public string Rate3 {
            get {
                return ((string)(this["Rate3"]));
            }
            set {
                this["Rate3"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\PPDatabase.mdf;Integrat" +
            "ed Security=True")]
        public string CNN {
            get {
                return ((string)(this["CNN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LIVING-ROOM\\SQLEXPRESS;Initial Catalog=\"E:\\ONEDRIVE\\VISUAL STUDIO PRO" +
            "GRAMS\\VISUAL STUDIO PROJECTS\\PEACE PORTAL PAYROLL BACKUP\\BIN\\DEBUG\\PPDATABASE.MD" +
            "F\";Integrated Security=True")]
        public string E__ONEDRIVE_VISUAL_STUDIO_PROGRAMS_VISUAL_STUDIO_PROJECTS_PEACE_PORTAL_PAYROLL_BACKUP_BIN_DEBUG_PPDATABASE_MDFConnectionString {
            get {
                return ((string)(this["E__ONEDRIVE_VISUAL_STUDIO_PROGRAMS_VISUAL_STUDIO_PROJECTS_PEACE_PORTAL_PAYROLL_BA" +
                    "CKUP_BIN_DEBUG_PPDATABASE_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LIVING-ROOM\\SQLEXPRESS;Initial Catalog=\"E:\\ONEDRIVE\\VISUAL STUDIO PRO" +
            "GRAMS\\VISUAL STUDIO PROJECTS\\PEACE PORTAL PAYROLL\\PPDATABASE.MDF\";Integrated Sec" +
            "urity=True")]
        public string E__ONEDRIVE_VISUAL_STUDIO_PROGRAMS_VISUAL_STUDIO_PROJECTS_PEACE_PORTAL_PAYROLL_PPDATABASE_MDFConnectionString {
            get {
                return ((string)(this["E__ONEDRIVE_VISUAL_STUDIO_PROGRAMS_VISUAL_STUDIO_PROJECTS_PEACE_PORTAL_PAYROLL_PP" +
                    "DATABASE_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=\"E:\\ONEDRIVE\\VISUAL STUDIO PROGRAMS\\VISU" +
            "AL STUDIO PROJECTS\\PEACE PORTAL PAYROLL\\BIN\\DEBUG\\PPDATABASE.MDF\";Integrated Sec" +
            "urity=True")]
        public string E__ONEDRIVE_VISUAL_STUDIO_PROGRAMS_VISUAL_STUDIO_PROJECTS_PEACE_PORTAL_PAYROLL_BIN_DEBUG_PPDATABASE_MDFConnectionString {
            get {
                return ((string)(this["E__ONEDRIVE_VISUAL_STUDIO_PROGRAMS_VISUAL_STUDIO_PROJECTS_PEACE_PORTAL_PAYROLL_BI" +
                    "N_DEBUG_PPDATABASE_MDFConnectionString"]));
            }
        }
    }
}
